# Generated by Django 6.0.7 on 2026-07-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0007_remove_disease_solution_alter_recommendation_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_result', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='knowledge.recommendation')),
                ('result_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='knowledge.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_user', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cf_expert', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cf_result', models.DecimalField(decimal_places=2, max_digits=3)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='diagnosis.diagnosis')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_details', to='knowledge.symptom')),
            ],
            options={
                'db_table': 'diagnosis_details',
                'ordering': ['id'],
            },
        ),
    ]
