# Generated by Django 6.0.7 on 2026-07-18 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_expert', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='knowledge.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='knowledge.symptom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('disease', 'symptom'), name='unique_disease_symptom')],
            },
        ),
    ]
