# Generated by Django 6.0.7 on 2026-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_status_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['disease', 'min_cf']},
        ),
        migrations.RemoveConstraint(
            model_name='recommendation',
            name='unique_disease_status',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='confidence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='max_cf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='min_cf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('disease', 'confidence'), name='unique_disease_confidence'),
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
