# Generated by Django 6.0.7 on 2026-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='confidence',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='max_cf',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='min_cf',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
