# Generated by Django 6.0.7 on 2026-07-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_alter_recommendation_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='solution',
        ),
        migrations.AlterModelTable(
            name='recommendation',
            table='recommendations',
        ),
    ]
